version: "3.7"
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - "27016:27017"
    volumes:
      - ./MONGO/data-node:/data/db
    command: mongod --noauth
    networks:
      - vastegrondnetwork
  nginx:
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./NGINX/content:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./NGINX/logs:/var/log/nginx
    depends_on:
      - vastegrond_api
    networks:
      - vastegrondnetwork
  vastegrond_api:
    image: node-api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=9000
    expose:
      - "9000"
    ports:
      - "9000:9000"
    volumes:
      - ./src:/app/src
    depends_on:
      - mongodb
    networks:
      - vastegrondnetwork
networks:
  vastegrondnetwork:
    driver: bridge
